/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gr.teicm.pm.clientsessionmanager;

import gr.teicm.pm.clientsessionmanager.controllers.ClientController;
import gr.teicm.pm.clientsessionmanager.model.Client;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.lang.Object;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.SystemUtils;

/**
 *
 * @author user
 */
public class ClientSessionManager extends javax.swing.JFrame {

    TimeWatch watch;
    ClientController controller;

    /**
     * Creates new form ClientSessionManager
     */
    public ClientSessionManager() {
        initComponents();
        containerPanel.removeAll();
        containerPanel.add(introPanel);
        containerPanel.repaint();
        containerPanel.revalidate();
        controller = new ClientController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        containerPanel = new javax.swing.JPanel();
        clientList = new javax.swing.JPanel();
        clientListScrollPane = new javax.swing.JScrollPane();
        clientListTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        newClientSession = new javax.swing.JPanel();
        clientName = new javax.swing.JTextField();
        clientNameLabel = new javax.swing.JLabel();
        caseDetailsLabel = new javax.swing.JLabel();
        caseDetails = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        chargingRateLabel = new javax.swing.JLabel();
        chargingRate = new javax.swing.JTextField();
        startSessionButton = new javax.swing.JToggleButton();
        finishSessionButton = new javax.swing.JToggleButton();
        lawyerOverview = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        introPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        containerPanel.setLayout(new java.awt.CardLayout());

        clientListTable.setModel(new javax.swing.table.DefaultTableModel(    new Object [][] {

        }    ,
        new String [] {
            "Client Name", "Charging rate", "Elapsed time", "Price"
        }
    ));
    clientListScrollPane.setViewportView(clientListTable);

    backButton.setText("Overview");
    backButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout clientListLayout = new javax.swing.GroupLayout(clientList);
    clientList.setLayout(clientListLayout);
    clientListLayout.setHorizontalGroup(
        clientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(clientListLayout.createSequentialGroup()
            .addGap(143, 143, 143)
            .addComponent(backButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addComponent(clientListScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    clientListLayout.setVerticalGroup(
        clientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientListLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(backButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(clientListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addGap(28, 28, 28))
    );

    containerPanel.add(clientList, "card7");

    clientName.setText("Client's Name");

    clientNameLabel.setText("Name");

    caseDetailsLabel.setText("case");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jTextArea1.setText("Case details here");
    caseDetails.setViewportView(jTextArea1);

    chargingRateLabel.setText("charging rate (per hour)");

    chargingRate.setText("2");

    startSessionButton.setText("Start session");
    startSessionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            startSessionButtonActionPerformed(evt);
        }
    });

    finishSessionButton.setText("finish session");
    finishSessionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            finishSessionButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout newClientSessionLayout = new javax.swing.GroupLayout(newClientSession);
    newClientSession.setLayout(newClientSessionLayout);
    newClientSessionLayout.setHorizontalGroup(
        newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newClientSessionLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newClientSessionLayout.createSequentialGroup()
                    .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clientNameLabel)
                        .addComponent(caseDetailsLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(caseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(newClientSessionLayout.createSequentialGroup()
                    .addComponent(chargingRateLabel)
                    .addGap(38, 38, 38)
                    .addComponent(chargingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newClientSessionLayout.createSequentialGroup()
                    .addComponent(startSessionButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(finishSessionButton)))
            .addContainerGap(36, Short.MAX_VALUE))
    );
    newClientSessionLayout.setVerticalGroup(
        newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newClientSessionLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(clientNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(caseDetailsLabel)
                .addComponent(caseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(chargingRateLabel)
                .addComponent(chargingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(startSessionButton)
                .addComponent(finishSessionButton))
            .addGap(19, 19, 19))
    );

    containerPanel.add(newClientSession, "card7");

    jButton2.setText("New Client Session");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    jToggleButton3.setText("Show Client Sessions");
    jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout lawyerOverviewLayout = new javax.swing.GroupLayout(lawyerOverview);
    lawyerOverview.setLayout(lawyerOverviewLayout);
    lawyerOverviewLayout.setHorizontalGroup(
        lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(lawyerOverviewLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jButton2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
            .addComponent(jToggleButton3)
            .addGap(24, 24, 24))
    );
    lawyerOverviewLayout.setVerticalGroup(
        lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(lawyerOverviewLayout.createSequentialGroup()
            .addGap(132, 132, 132)
            .addGroup(lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2)
                .addComponent(jToggleButton3))
            .addContainerGap(120, Short.MAX_VALUE))
    );

    containerPanel.add(lawyerOverview, "card5");

    jLabel1.setText("I am ");

    jButton3.setText("Lawyer");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout introPanelLayout = new javax.swing.GroupLayout(introPanel);
    introPanel.setLayout(introPanelLayout);
    introPanelLayout.setHorizontalGroup(
        introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(introPanelLayout.createSequentialGroup()
            .addGroup(introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(introPanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(introPanelLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(jButton3)))
            .addContainerGap(85, Short.MAX_VALUE))
    );
    introPanelLayout.setVerticalGroup(
        introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(introPanelLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(jLabel1)
            .addGap(18, 18, 18)
            .addComponent(jButton3)
            .addContainerGap(183, Short.MAX_VALUE))
    );

    containerPanel.add(introPanel, "card2");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton1)
                .addContainerGap(160, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton1)
                .addContainerGap(149, Short.MAX_VALUE)))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showComponent(newClientSession);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void startSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSessionButtonActionPerformed
        // start time
        this.watch = TimeWatch.start();
    }//GEN-LAST:event_startSessionButtonActionPerformed

    private void finishSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishSessionButtonActionPerformed
        long passedTimeInSeconds = this.watch.getTime(TimeUnit.SECONDS);
        controller.getClientDetailsFromForm(clientName.getText(), caseDetails.getToolTipText(), chargingRate.getText(), passedTimeInSeconds);
        showComponent(introPanel);
    }//GEN-LAST:event_finishSessionButtonActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) clientListTable.getModel();
        List<Client> clients = controller.getClients();
        for (Client c : clients) {
            model.addRow(new Object[]{c.getName(), Long.toString(c.getChargingRate()), Long.toString(c.getElapsedTime()), Long.toString(c.getElapsedTime() * c.getChargingRate())});
        }
        Object columnnames[] = {
            "Client Name", "Charging rate", "Elapsed time", "Price"
        };
        clientListTable.setModel(model);
        showComponent(clientList);

    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // do something
        //  long passedTimeInMs = watch.getTime();
        //long passedTimeInSeconds = watch.getTime(TimeUnit.SECONDS);
        // jLabel1.setText(Long.toString(passedTimeInSeconds));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showComponent(lawyerOverview);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (SystemUtils.IS_OS_LINUX) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                }
                if (SystemUtils.IS_OS_WINDOWS) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                }
                if (SystemUtils.IS_OS_MAC_OSX || SystemUtils.IS_OS_MAC) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientSessionManager().setVisible(true);
            }
        });
    }

    private void showComponent(JComponent component) {
        containerPanel.removeAll();
        containerPanel.add(component);
        containerPanel.repaint();
        containerPanel.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane caseDetails;
    private javax.swing.JLabel caseDetailsLabel;
    private javax.swing.JTextField chargingRate;
    private javax.swing.JLabel chargingRateLabel;
    private javax.swing.JPanel clientList;
    private javax.swing.JScrollPane clientListScrollPane;
    private javax.swing.JTable clientListTable;
    private javax.swing.JTextField clientName;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JToggleButton finishSessionButton;
    private javax.swing.JPanel introPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel lawyerOverview;
    private javax.swing.JPanel newClientSession;
    private javax.swing.JToggleButton startSessionButton;
    // End of variables declaration//GEN-END:variables
}
