/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gr.teicm.pm.clientsessionmanager.ui;

import gr.teicm.pm.clientsessionmanager.logic.TimeWatch;
import gr.teicm.pm.clientsessionmanager.logic.controllers.ClientController;
import java.util.concurrent.TimeUnit;
import java.lang.Object;
import javax.swing.JComponent;
import org.apache.commons.lang3.SystemUtils;

/**
 *
 * @author user
 */
public class ClientSessionManager extends javax.swing.JFrame {

    TimeWatch watch;
    ClientController controller;

    /**
     * Creates new form ClientSessionManager
     */
    public ClientSessionManager() {
        initComponents();
        containerPanel.removeAll();
        containerPanel.add(introPanel);
        containerPanel.repaint();
        containerPanel.revalidate();
        controller = new ClientController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        clientList = new javax.swing.JPanel();
        clientListScrollPane = new javax.swing.JScrollPane();
        clientListTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        newClientSession = new javax.swing.JPanel();
        clientName = new javax.swing.JTextField();
        clientNameLabel = new javax.swing.JLabel();
        caseDetailsLabel = new javax.swing.JLabel();
        caseDetails = new javax.swing.JScrollPane();
        caseDetailsArea = new javax.swing.JTextArea();
        chargingRateLabel = new javax.swing.JLabel();
        chargingRate = new javax.swing.JTextField();
        startSessionButton = new javax.swing.JToggleButton();
        finishSessionButton = new javax.swing.JToggleButton();
        lawyerOverview = new javax.swing.JPanel();
        newClient = new javax.swing.JButton();
        toIntroButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        introPanel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        lawyerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        containerPanel.setLayout(new java.awt.CardLayout());

        clientListTable.setModel(new javax.swing.table.DefaultTableModel(    new Object [][] {

        }    ,
        new String [] {
            "Client Name", "Charging rate", "Elapsed time", "Price"
        }
    ));
    clientListScrollPane.setViewportView(clientListTable);

    backButton.setText("Go Back");
    backButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout clientListLayout = new javax.swing.GroupLayout(clientList);
    clientList.setLayout(clientListLayout);
    clientListLayout.setHorizontalGroup(
        clientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(clientListLayout.createSequentialGroup()
            .addGap(143, 143, 143)
            .addComponent(backButton)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addComponent(clientListScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    clientListLayout.setVerticalGroup(
        clientListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientListLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(backButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(clientListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addGap(28, 28, 28))
    );

    containerPanel.add(clientList, "card7");

    clientName.setText("Client's Name");

    clientNameLabel.setText("Name");

    caseDetailsLabel.setText("case");

    caseDetailsArea.setColumns(20);
    caseDetailsArea.setRows(5);
    caseDetailsArea.setText("Case details here");
    caseDetails.setViewportView(caseDetailsArea);

    chargingRateLabel.setText("charging rate (per hour)");

    chargingRate.setText("2");

    startSessionButton.setText("Start session");
    startSessionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            startSessionButtonActionPerformed(evt);
        }
    });

    finishSessionButton.setText("finish session");
    finishSessionButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            finishSessionButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout newClientSessionLayout = new javax.swing.GroupLayout(newClientSession);
    newClientSession.setLayout(newClientSessionLayout);
    newClientSessionLayout.setHorizontalGroup(
        newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newClientSessionLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(newClientSessionLayout.createSequentialGroup()
                    .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(clientNameLabel)
                        .addComponent(caseDetailsLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(caseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(newClientSessionLayout.createSequentialGroup()
                    .addComponent(chargingRateLabel)
                    .addGap(38, 38, 38)
                    .addComponent(chargingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(newClientSessionLayout.createSequentialGroup()
                    .addComponent(startSessionButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(finishSessionButton)))
            .addContainerGap(36, Short.MAX_VALUE))
    );
    newClientSessionLayout.setVerticalGroup(
        newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(newClientSessionLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(clientNameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(caseDetailsLabel)
                .addComponent(caseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(chargingRateLabel)
                .addComponent(chargingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addGroup(newClientSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(startSessionButton)
                .addComponent(finishSessionButton))
            .addGap(19, 19, 19))
    );

    containerPanel.add(newClientSession, "card7");

    newClient.setText("New Client Session");
    newClient.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            newClientActionPerformed(evt);
        }
    });

    toIntroButton.setText("Go Back");
    toIntroButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            toIntroButtonActionPerformed(evt);
        }
    });

    jButton1.setText("Show Client Sessions");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout lawyerOverviewLayout = new javax.swing.GroupLayout(lawyerOverview);
    lawyerOverview.setLayout(lawyerOverviewLayout);
    lawyerOverviewLayout.setHorizontalGroup(
        lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(lawyerOverviewLayout.createSequentialGroup()
            .addGroup(lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lawyerOverviewLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(newClient)
                    .addGap(36, 36, 36)
                    .addComponent(jButton1))
                .addGroup(lawyerOverviewLayout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(toIntroButton)))
            .addContainerGap(41, Short.MAX_VALUE))
    );
    lawyerOverviewLayout.setVerticalGroup(
        lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(lawyerOverviewLayout.createSequentialGroup()
            .addGap(132, 132, 132)
            .addGroup(lawyerOverviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(newClient)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
            .addComponent(toIntroButton)
            .addGap(31, 31, 31))
    );

    containerPanel.add(lawyerOverview, "card5");

    label.setText("I am a");

    lawyerButton.setText("Lawyer");
    lawyerButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lawyerButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout introPanelLayout = new javax.swing.GroupLayout(introPanel);
    introPanel.setLayout(introPanelLayout);
    introPanelLayout.setHorizontalGroup(
        introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(introPanelLayout.createSequentialGroup()
            .addGroup(introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(introPanelLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(introPanelLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(lawyerButton)))
            .addContainerGap(85, Short.MAX_VALUE))
    );
    introPanelLayout.setVerticalGroup(
        introPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(introPanelLayout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addComponent(label)
            .addGap(18, 18, 18)
            .addComponent(lawyerButton)
            .addContainerGap(183, Short.MAX_VALUE))
    );

    containerPanel.add(introPanel, "card2");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClientActionPerformed
        showComponent(newClientSession);
    }//GEN-LAST:event_newClientActionPerformed

    private void startSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSessionButtonActionPerformed
        // start time
        this.watch = TimeWatch.start();
    }//GEN-LAST:event_startSessionButtonActionPerformed

    private void finishSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishSessionButtonActionPerformed
        long passedTimeInSeconds = this.watch.getTime(TimeUnit.SECONDS);
        controller.getClientDetailsFromForm(clientName.getText(), caseDetailsArea.getText(), chargingRate.getText(), passedTimeInSeconds);
        showComponent(introPanel);
    }//GEN-LAST:event_finishSessionButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        showComponent(lawyerOverview);
    }//GEN-LAST:event_backButtonActionPerformed

    private void lawyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lawyerButtonActionPerformed
        showComponent(lawyerOverview);
    }//GEN-LAST:event_lawyerButtonActionPerformed

    private void toIntroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toIntroButtonActionPerformed
        showComponent(introPanel);
    }//GEN-LAST:event_toIntroButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clientListTable.setModel(controller.getClientsModel());
        showComponent(clientList);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (SystemUtils.IS_OS_LINUX) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
                }
                if (SystemUtils.IS_OS_WINDOWS) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                }
                if (SystemUtils.IS_OS_MAC_OSX || SystemUtils.IS_OS_MAC) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSessionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientSessionManager().setVisible(true);
            }
        });
    }

    private void showComponent(JComponent component) {
        containerPanel.removeAll();
        containerPanel.add(component);
        containerPanel.repaint();
        containerPanel.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane caseDetails;
    private javax.swing.JTextArea caseDetailsArea;
    private javax.swing.JLabel caseDetailsLabel;
    private javax.swing.JTextField chargingRate;
    private javax.swing.JLabel chargingRateLabel;
    private javax.swing.JPanel clientList;
    private javax.swing.JScrollPane clientListScrollPane;
    private javax.swing.JTable clientListTable;
    private javax.swing.JTextField clientName;
    private javax.swing.JLabel clientNameLabel;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JToggleButton finishSessionButton;
    private javax.swing.JPanel introPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label;
    private javax.swing.JButton lawyerButton;
    private javax.swing.JPanel lawyerOverview;
    private javax.swing.JButton newClient;
    private javax.swing.JPanel newClientSession;
    private javax.swing.JToggleButton startSessionButton;
    private javax.swing.JButton toIntroButton;
    // End of variables declaration//GEN-END:variables
}
